version: '3'
services:
    php_mw_sensors:
      container_name: php_mw_sensors
      image: mwillms/my.php:1.0
      build:
        context: ./Dockerfiles
        dockerfile: PHP_s_Dockerfile
      ports:
        - '18887:80'
        #user: root
      restart: unless-stopped
      volumes:
        - ./Dockerfiles/php_src:/var/www
        - ./Dockerfiles/shared_data:/shared_data
        - ./Dockerfiles/shared_data/big_data:/shared_data/big_data
        - ./Dockerfiles/shared_data/remote_data:/shared_data/remote_data
      networks:
        - my_network


    php_mw_ask_geanny:
      container_name: php_mw_ask_geanny
      image: mwillms/my.php:1.0
      build:
        context: ./Dockerfiles
        dockerfile: PHP_s_Dockerfile
      ports:
        - '18888:80'
        #user: root
      restart: unless-stopped
      volumes:
        - ./Dockerfiles/php_src:/var/www
        - ./Dockerfiles/shared_data:/shared_data
        - ./Dockerfiles/shared_data/big_data:/shared_data/big_data
        - ./Dockerfiles/shared_data/remote_data:/shared_data/remote_data
      networks:
        - my_network

volumes:
    shared_data:
    big_data:
    remote_data:

networks:
    my_network:




